# default ('prod' profile) base config
quarkus:
  log:
    category:
      "org.apache.http":
        level: DEBUG
      "com.bytes.bag.brown.quarkus":
        level: INFO
  http:
    port: 8080
    access-log:
      enabled: true
      exclude-pattern: '/q/.*' # exclude the health endpoints from the access log output
      pattern: '%{REMOTE_HOST} %l %{REMOTE_USER} %{DATE_TIME} "%{REQUEST_LINE}" %{RESPONSE_CODE} %b %{RESPONSE_TIME} %T'
    record-request-start-time: true
  smallrye-health:
    enabled: true # /q/health/live /q/health/ready  /q/health/well  /q/health-ui

'%dev':
  quarkus:
    dev-ui:
      hosts: 8080-ddjonline-brownbagbytes-8owzbyi4a17.ws-us118.gitpod.io # update this to match your GitPod session host name